//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;

namespace ToolBX.Reflection4Humans.Extensions.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Exceptions {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ToolBX.Reflection4Humans.Extensions.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use method {0} : accessModifier is unrecognized and unsupported.
        /// </summary>
        internal static string AccessModifierUnsupported {
            get {
                return ResourceManager.GetString("AccessModifierUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use method {0} : parameter {1} is mandatory.
        /// </summary>
        internal static string CannotUseMethodBecauseParamaterIsMandatory {
            get {
                return ResourceManager.GetString("CannotUseMethodBecauseParamaterIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; cannot be cast to a field.
        /// </summary>
        internal static string MemberCannotBeCastToField {
            get {
                return ResourceManager.GetString("MemberCannotBeCastToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; cannot be cast to a property.
        /// </summary>
        internal static string MemberCannotBeCastToProperty {
            get {
                return ResourceManager.GetString("MemberCannotBeCastToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MemberInfoTypeNotSupported {
            get {
                return ResourceManager.GetString("MemberInfoTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is neither property nor field.
        /// </summary>
        internal static string MemberIsNeitherPropertyNorField {
            get {
                return ResourceManager.GetString("MemberIsNeitherPropertyNorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use method {0} : member kind &apos;{1}&apos; is unsupported.
        /// </summary>
        internal static string MemberKindUnsupported {
            get {
                return ResourceManager.GetString("MemberKindUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get property path : property &apos;{0}&apos; was not found on type &apos;{1}&apos;.
        /// </summary>
        internal static string PropertyNotFoundOnType {
            get {
                return ResourceManager.GetString("PropertyNotFoundOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is a write-only property and therefore cannot be read.
        /// </summary>
        internal static string UsingGetOnWriteOnlyProperty {
            get {
                return ResourceManager.GetString("UsingGetOnWriteOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is a read-only property and therefore cannot be written to.
        /// </summary>
        internal static string UsingSetOnReadOnlyProperty {
            get {
                return ResourceManager.GetString("UsingSetOnReadOnlyProperty", resourceCulture);
            }
        }
    }
}
