name: Publish to NuGet

on:
  push:
    branches:
      - main
      
env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --configuration Release
      
    - name: Pack project
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      
    - name: Publish to NuGet.org
      run: | 
        dotnet nuget push .${{ env.NuGetDirectory }}/Reflection4Humans.Extensions.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push .${{ env.NuGetDirectory }}/Reflection4Humans.TypeFetcher.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
