name: Publish to NuGet

on:
  push:
    branches:
      - master
      
env:
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --configuration Release
      
    - name: Pack projects
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      
    - name: Publish to NuGet.org
      run: | 
        nuget push ${{ env.NuGetDirectory }}/ToolBX.Reflection4Humans.Extensions.*.nupkg -Source 'https://api.nuget.org/v3/index.json' --skip-duplicate -ApiKey ${{secrets.NUGET_API_KEY}} 
        nuget push ${{ env.NuGetDirectory }}/ToolBX.Reflection4Humans.TypeFetcher.*.nupkg -Source 'https://api.nuget.org/v3/index.json' --skip-duplicate -ApiKey ${{secrets.NUGET_API_KEY}} 
